name: Build dcgm-exporter

on:
  release:
    types: created

env:
  DCGM_EXPORTER_VERSION: '3.3.6-3.4.2'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NVIDIA/dcgm-exporter
          ref: tags/${{ env.DCGM_EXPORTER_VERSION }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.21.0'
      - name: Build
        run: make binary
      - name: Release binary
        uses: softprops/action-gh-release@v2
        with:
          files: cmd/dcgm-exporter/dcgm-exporter
